#!/usr/bin/env bash
# cs-watch.sh — watch for messages from the partner session.
#
#   usage:  cs-watch.sh <partner_role>
#           cs-watch.sh bob            # run by alice, watching for bob's messages
#
# ⛔ RUN THIS UNDER THE Monitor TOOL WITH persistent:true, NOT AS A PLAIN BACKGROUND JOB.
# Every line it prints becomes one notification that WAKES the session that armed it —
# including a session sitting idle. That wake is the whole mechanism.
#
# ⭐ THE POLLING HAPPENS IN THIS SHELL, NOT IN THE MODEL. An empty poll prints nothing and
# therefore costs ZERO tokens. A model turn happens only when a line is actually printed.
# That is why a 2-second poll is affordable and a scheduled "check for messages" prompt
# is not: the latter costs a full turn every time it fires, finding nothing.
set -u

DIR="${CS_DIR:-.claude/cross-session}"
PARTNER="${1:?partner role name required, e.g. bob}"
PARTNER_LOG="${2:-}"

POLL="${CS_POLL:-2}"                # seconds between checks
MAX_INLINE="${CS_MAX_INLINE:-150}"  # print bodies inline up to this many lines
QUIET_MIN="${CS_QUIET_MIN:-15}"     # partner silent this long -> alert
REPORT_MIN="${CS_REPORT_MIN:-25}"   # partner busy but not reporting -> alert
REALERT_MIN="${CS_REALERT_MIN:-30}" # minimum gap between repeat alerts

mkdir -p "$DIR"
SEEN="$(mktemp)"; NEW="$(mktemp)"
trap 'rm -f "$SEEN" "$NEW"' EXIT

list_msgs() { ls -1 "$DIR"/${PARTNER}_*.md 2>/dev/null | sort; }
now() { date +%s; }
mtime() { stat -c %Y "$1" 2>/dev/null || echo 0; }

# Newest message from EITHER side. The "not reporting" clock must measure time since
# THE BALL WAS PASSED, not time since the partner last spoke — otherwise sending a message
# and then alerting because the partner has not replied within seconds is a false positive
# generated by your own message.
newest_msg_ts() {
  local newest=0 m
  for f in "$DIR"/*_*.md; do
    [ -e "$f" ] || continue
    m=$(mtime "$f"); [ "$m" -gt "$newest" ] && newest=$m
  done
  echo "$newest"
}

# --- startup ---------------------------------------------------------------
list_msgs > "$SEEN"
pending=$(wc -l < "$SEEN" | tr -d ' ')
if [ "$pending" -gt 0 ]; then
  # On a RE-ARM these replay. Deliberately listed rather than hidden: showing an old
  # message costs a glance, hiding a new one costs a night.
  echo "WATCHER ARMED for ${PARTNER}_*.md — ${pending} file(s) ALREADY PRESENT (replayed on arm, NOT new mail — check your last answered number before acting): $(tr '\n' ' ' < "$SEEN")"
else
  echo "WATCHER ARMED for ${PARTNER}_*.md in ${DIR} — none pending, waiting."
fi

last_msg_ts=$(now)
last_quiet_alert=0
last_report_alert=0
last_dead_log_alert=0

# --- watch loop ------------------------------------------------------------
while true; do
  sleep "$POLL"

  # 1) NEW MESSAGES — the primary job.
  if list_msgs > "$NEW" 2>/dev/null; then
    if ! cmp -s "$SEEN" "$NEW"; then
      comm -13 "$SEEN" "$NEW" 2>/dev/null | while IFS= read -r f; do
        [ -n "$f" ] || continue
        n=$(wc -l < "$f" | tr -d ' ')
        # ⭐ THE BODY IS PRINTED INLINE, NOT JUST ANNOUNCED. Monitor batches stdout lines
        # within 200ms into ONE notification, so the whole message arrives as a single
        # event and the reader needs no follow-up file read. Announcing only the filename
        # costs an entire wasted tool round-trip per message.
        echo "NEW MESSAGE >> $f  ($n lines)"
        if [ "$n" -le "$MAX_INLINE" ]; then
          cat "$f"
        else
          head -n "$MAX_INLINE" "$f"
          echo "... [TRUNCATED at ${MAX_INLINE} of ${n} lines — open $f for the rest]"
        fi
        echo "--- end $f · reply with the next numbered file ---"
      done
      cp "$NEW" "$SEEN"
      last_msg_ts=$(now)
      last_report_alert=0
      # A dispatch ends any declared quiet period: the partner has work again.
      rm -f "$DIR/.quiet"
    fi
  fi

  # 2) WATCHDOG — optional; needs the partner to have run cs-register.sh.
  #
  # ⛔ A DECLARED QUIET PERIOD SUPPRESSES IT:  touch .claude/cross-session/.quiet
  # At a terminal state a quiet partner is the DESIRED outcome, and no watchdog can tell
  # "silent because instructed" from "silent because stuck". Write the state down instead
  # of inferring it. Any new message from either side clears the flag automatically, so it
  # cannot be left on by accident and mask a real stall.
  [ -f "$DIR/.quiet" ] && continue

  # Resolved EVERY iteration, not once at startup, so a partner that registers later is
  # still picked up.
  LOG="$PARTNER_LOG"
  [ -n "$LOG" ] || LOG=$(cat "$DIR/.${PARTNER}.transcript" 2>/dev/null || true)
  [ -n "$LOG" ] || continue
  t=$(now)

  if [ ! -f "$LOG" ]; then
    if [ $(( t - last_dead_log_alert )) -ge $(( REALERT_MIN * 60 )) ]; then
      echo "WATCHDOG: partner transcript not found at ${LOG} — the session was probably replaced. Partner must re-run cs-register.sh."
      last_dead_log_alert=$t
    fi
    continue
  fi

  partner_idle=$(( t - $(mtime "$LOG") ))
  lm=$(newest_msg_ts); [ "${lm:-0}" -gt 0 ] || lm=$last_msg_ts
  since_msg=$(( t - lm ))

  # 2a) Partner has done nothing at all: stuck, waiting, or dead.
  if [ "$partner_idle" -ge $(( QUIET_MIN * 60 )) ] \
     && [ $(( t - last_quiet_alert )) -ge $(( REALERT_MIN * 60 )) ]; then
    echo "WATCHDOG: partner INACTIVE for $(( partner_idle / 60 ))m (no transcript activity). Stuck, blocked, or waiting on input."
    last_quiet_alert=$t
  fi

  # 2b) Partner is working but has not reported: the divergence case.
  if [ "$partner_idle" -lt 300 ] && [ "$since_msg" -ge $(( REPORT_MIN * 60 )) ] \
     && [ $(( t - last_report_alert )) -ge $(( REALERT_MIN * 60 )) ]; then
    echo "WATCHDOG: partner ACTIVE but no message in $(( since_msg / 60 ))m — it may have diverged or forgotten to report."
    last_report_alert=$t
  fi
done
